name: Coveralls

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  test:
    name: Run Unit Tests and Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --trusted-host pypi.python.org --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
    - name: Test with pytest
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        find -name '*.pyc' -delete
        find -name __pycache__ -delete
        export DJANGO_SETTINGS_MODULE="settings"
        python setup.py develop
        pytest --cov=. --cov-config=coverage.ini
        coveralls --rcfile=coverage.ini
